In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
arr1 = np.arange(9).reshape((3,3))

In [4]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis =1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis =0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2], index=['T','U','V'])
ser2 = Series([3,4], index= ['X','Y'])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [13]:
pd.concat([ser1,ser2,ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [14]:
pd.concat([ser1,ser2],axis = 1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [15]:
pd.concat([ser1,ser2],keys = ['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [16]:
pd.concat([ser1,ser2],axis = 1,keys = ['cat1','cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [17]:
dframe1 = DataFrame(np.random.randn(4,3),columns = ['x','y','z'])

In [18]:
dframe1

x         y         z
0  0.723786 -0.840820  0.420430
1  0.824724  0.147790  0.466941
2  0.843178 -0.582921 -0.865770
3 -0.324868  1.596162 -0.785415

In [19]:
dframe2 = DataFrame(np.random.randn(3,3),columns = ['y','q','x'])

In [20]:
dframe2

y         q         x
0 -1.132737 -0.474230  0.714330
1  0.284967 -0.792538 -1.529621
2 -0.934233  1.253939 -1.017698

In [21]:
pd.concat([dframe1, dframe2])

q         x         y         z
0       NaN  0.723786 -0.840820  0.420430
1       NaN  0.824724  0.147790  0.466941
2       NaN  0.843178 -0.582921 -0.865770
3       NaN -0.324868  1.596162 -0.785415
0 -0.474230  0.714330 -1.132737       NaN
1 -0.792538 -1.529621  0.284967       NaN
2  1.253939 -1.017698 -0.934233       NaN

In [22]:
pd.concat([dframe1, dframe2], ignore_index = True)

q         x         y         z
0       NaN  0.723786 -0.840820  0.420430
1       NaN  0.824724  0.147790  0.466941
2       NaN  0.843178 -0.582921 -0.865770
3       NaN -0.324868  1.596162 -0.785415
4 -0.474230  0.714330 -1.132737       NaN
5 -0.792538 -1.529621  0.284967       NaN
6  1.253939 -1.017698 -0.934233       NaN