In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

In [2]:
x = np.array([1,2,3])

In [3]:
x

array([1, 2, 3])

In [4]:
y = np.array([2,3.9,6.1])

In [5]:
y

array([2. , 3.9, 6.1])

In [6]:
x.mean()

2.0

In [7]:
y.mean()

4.0

In [8]:
xc = x - x.mean()

In [9]:
xc

array([-1.,  0.,  1.])

In [10]:
yc = y - y.mean()

In [11]:
yc

array([-2. , -0.1,  2.1])